### ISSUE TITLE
"OSError: [Errno 24] Too many open files" SyntaxWarning error in addon from patreon (for v2.1 anki)

### ISSUE THREAD

**Issue by srghma** [glutanimate/pdf-glossary#15]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.36 (c505894b) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-02-13 16:25:25
Add-ons possibly involved: ⁨pdf_glossary⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/taskman.py", line 87, in _on_closures_pending
  File "aqt/taskman.py", line 59, in <lambda>
  File "aqt/exporting.py", line 163, in on_done
  File "concurrent/futures/_base.py", line 432, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "aqt/exporting.py", line 157, in do_export
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/exporter.py", line 342, in exportInto
  File "anki/exporting.py", line 47, in exportInto
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/exporter.py", line 235, in doExport
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/exporter.py", line 335, in writeExportFile
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/document.py", line 96, in pisaDocument
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/document.py", line 59, in pisaStory
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 759, in pisaParser
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 700, in pisaLoop
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 644, in pisaLoop
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 644, in pisaLoop
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 644, in pisaLoop
  [Previous line repeated 5 more times]
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 514, in pisaLoop
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/parser.py", line 124, in pisaGetAttributes
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/context.py", line 818, in getFile
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/util.py", line 738, in getFile
  File "/home/srghma/.local/share/Anki2/addons21/pdf_glossary/_vendor/xhtml2pdf/util.py", line 689, in __init__
OSError: [Errno 24] Too many open files: '/home/srghma/.local/share/Anki2/User 1/collection.media/lf_26366.gif'
```

when exporting as `.htm`

hm, but it seems like file was written anyway :+1:

**Comment by srghma** [comment]
there somewhere a memory leak
